# Welcome to Jekyll!


# Site settings
title: SAFE Engineering
description: |
  Proving that Dijkstra was wrong
owner: SAFE Engineering # or company name
first_published: 2018  # if migrating another site, the year of your first publish
email: info@sage.engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "safe.engineering" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/
  github: https://github.com/
  linkedin-square: https://linkedin.com/
  facebook-official: https://facebook.com/
  google-plus-square: https://plus.google.com/

# Build settings
markdown: kramdown
#sass:
#  style: compressed
